name: 'Sync with Upstream'

on:
  schedule:
    - cron: '0 8 * * 1'
    
  workflow_dispatch:
  
jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: 'Syncs main branch with upstream'
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Sync w/ upstream
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        target_sync_branch: main
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_branch: main
        upstream_sync_repo: LLNL/hatchet-tutorial
